@AgroMonitor_HostAddress = http://localhost:5107

GET {{AgroMonitor_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{AgroMonitor_HostAddress}}/api/device

###

GET {{AgroMonitor_HostAddress}}/api/device

###

@id=0
GET {{AgroMonitor_HostAddress}}/api/sensorreadings/{{id}}

###

GET {{AgroMonitor_HostAddress}}/api/sensorreadings

###

GET {{AgroMonitor_HostAddress}}/api/sensorreadings

###

POST {{AgroMonitor_HostAddress}}/api/device
Content-Type: application/json
{
    "deviceIdentifier" : "0345",
    "name" : "Arduino",
    "location" : "Naguru"
}

###

POST {{AgroMonitor_HostAddress}}/api/device
Content-Type: application/json

{
      "deviceIdentifier" : "0675",
      "name" : "Arduino",
      "location" : "Naguru"
}

###

POST {{AgroMonitor_HostAddress}}/api/device
Content-Type: application/json

{
      "deviceIdentifier" : "0903",
      "name" : "Rasberry PI 4",
      "location" : "Kisaasi"
}

###

DELETE {{AgroMonitor_HostAddress}}/api/device/{{3}}

###

DELETE {{AgroMonitor_HostAddress}}/api/device/3

###

POST {{AgroMonitor_HostAddress}}/api/device
Content-Type: application/json

{
      "deviceIdentifier" : "0582",
      "name" : "Rasberry PI 3",
      "location" : "Bukoto"
}

###

GET {{AgroMonitor_HostAddress}}/api/device

###

GET {{AgroMonitor_HostAddress}}/api/device/4


###

GET {{AgroMonitor_HostAddress}}/api/sensorreadings

###

POST {{AgroMonitor_HostAddress}}/api/sensorreadings
Content-Type: application/json

{
  "deviceIdentifier": "0675",
  "readings": [
    {
      "sensorType": "moisture",
      "value": 45.5
    },
    {
      "sensorType": "temperature",
      "value": 25.0
    },
    {
        "sensorType" : "humidity",
        "value" : 30
    }
  ]
}

###

POST {{AgroMonitor_HostAddress}}/api/sensorreadings
Content-Type: application/json

{
  "deviceIdentifier": "0345",
  "readings": [
    {
      "sensorType": "moisture",
      "value": 50.4
    },
    {
      "sensorType": "temperature",
      "value": 27.9
    },
    {
        "sensorType" : "humidity",
        "value" : 18
    }
  ]
}

###

GET {{AgroMonitor_HostAddress}}/api/sensorreadings

###

POST {{AgroMonitor_HostAddress}}/api/sensorreadings
Content-Type: application/json

{
  "deviceIdentifier": "0582",
  "readings": [
    {
      "sensorType": "moisture",
      "value": 52.7
    },
    {
      "sensorType": "temperature",
      "value": 28.9
    },
    {
        "sensorType" : "humidity",
        "value" : 2
    }
  ]
}

###

POST {{AgroMonitor_HostAddress}}/api/device
Content-Type: application/json

{
  
      "deviceIdentifier" : "0309",
      "name" : "Esp 32",
      "location" : "Kira"
}

###

GET {{AgroMonitor_HostAddress}}/api/device

###

POST {{AgroMonitor_HostAddress}}/api/sensorreadings
Content-Type: application/json

{
  //SensorDataPayload
}

###

GET {{AgroMonitor_HostAddress}}/api/sensorreadings/3

###

GET {{AgroMonitor_HostAddress}}/api/device

###

GET {{AgroMonitor_HostAddress}}/api/device

###

GET {{AgroMonitor_HostAddress}}/api/device

###

GET {{AgroMonitor_HostAddress}}/api/device

###

GET {{AgroMonitor_HostAddress}}/api/device

###

GET {{AgroMonitor_HostAddress}}/api/device

###

GET {{AgroMonitor_HostAddress}}/api/sensorreadings/3

###

GET {{AgroMonitor_HostAddress}}/api/sensorreadings

###

GET {{AgroMonitor_HostAddress}}/api/sensorreadings/{{id}}

###

POST {{AgroMonitor_HostAddress}}/api/customerpackage
Content-Type: application/json

{
  "packageId": 1,
  "customerId": 1
}

###

POST {{AgroMonitor_HostAddress}}/api/sensorreadings
Content-Type: application/json

{
  "DeviceIdentifier": "CU32949",
  "Readings": [
    {
      "SensorType": "Temperature",
      "Value": 7
    },
    {
      "SensorType": "Humidity",
      "Value": 5
    },
    {
      "SensorType": "Moisture",
      "Value": 90
    }
  ]
}

###

POST {{AgroMonitor_HostAddress}}/api/sensorreadings
Content-Type: application/json

{
  //SensorDataPayload
}

###

POST {{AgroMonitor_HostAddress}}/api/sensorreadings
Content-Type: application/json

{
  //SensorDataPayload
}

###

POST {{AgroMonitor_HostAddress}}/api/sensorreadings
Content-Type: application/json

{
  //SensorDataPayload
}

###

POST {{AgroMonitor_HostAddress}}/api/devicefordisplays
Content-Type: application/json

{
  "name":"Watcher 100",
  "brandCode":"Z-100"
}

###

POST {{AgroMonitor_HostAddress}}/api/device
Content-Type: application/json

{
  [
  {
    "BrandCode": "ABC123",
    "Name": "Soil Sensor",
    "DeviceIdentifier": "CU12345"
  },
  {
    "BrandCode": "DEF456",
    "Name": "Weather Station",
    "DeviceIdentifier": "CU67890"
  },
  {
    "BrandCode": "GHI789",
    "Name": "Irrigation Controller",
    "DeviceIdentifier": "CU54321"
  }
]

}

###

POST {{AgroMonitor_HostAddress}}/api/device/bulk
Content-Type: application/json

[
  {
    "BrandCode": "ABC123",
    "Name": "Soil Sensor",
    "DeviceIdentifier": "CU12345"
  },
  {
    "BrandCode": "DEF456",
    "Name": "Weather Station",
    "DeviceIdentifier": "CU67890"
  },
  {
    "BrandCode": "GHI789",
    "Name": "Irrigation Controller",
    "DeviceIdentifier": "CU54321"
  }
]

###

POST {{AgroMonitor_HostAddress}}/api/package/bulk
Content-Type: application/json

[
  {
    "Name": "Basic Monitoring",
    "Description": "Includes soil moisture and temperature sensors",
    "Price": 49.99,
    "DeviceId": 7
  },
  {
    "Name": "Advanced Analytics",
    "Description": "Includes weather station, data logging, and cloud sync",
    "Price": 129.99,
    "DeviceId": 8
  },
  {
    "Name": "Full Automation",
    "Description": "Complete system with irrigation controller and AI recommendations",
    "Price": 299.99,
    "DeviceId": 9
  }
]


###

POST {{AgroMonitor_HostAddress}}/api/customerpackage/bulk
Content-Type: application/json

[
  {
    "PackageId": 6,
    "CustomerId": 13
  },
  {
    "PackageId": 7,
    "CustomerId": 13
  },
  {
    "PackageId": 8,
    "CustomerId": 13
  }
]


###

POST {{AgroMonitor_HostAddress}}/api/sensorreadings
Content-Type: application/json

{
  "DeviceIdentifier": "CU87421",
  "Readings": [
    {
      "SensorType": "Temperature",
      "Value": 23.5
    },
    {
      "SensorType": "Humidity",
      "Value": 60.2
    },
    {
      "SensorType": "Moisture",
      "Value": 45.7
    }
  ]
}


###

GET {{AgroMonitor_HostAddress}}/api/sensorreadings

###

GET {{AgroMonitor_HostAddress}}/api/device

###

GET {{AgroMonitor_HostAddress}}/api/device

###

GET {{AgroMonitor_HostAddress}}/api/device/5

###
POST {{AgroMonitor_HostAddress}}/api/sms
Content-Type: application/json
x-signature: sha256=7f0f827d-3a19-47f1-b91e-28fe79e5a4b7
{
  "smsId": "sms123",
  "sender": "+123456789",
  "message": "deviceId=dev001;temperature=25.5;humidity=67",
  "receivedAt": "2025-05-23T12:00:00Z",
  "deviceId": "dev001",
  "webhookSubscriptionId": "webhook123",
  "webhookEvent": "sms.received"
}



###

POST {{AgroMonitor_HostAddress}}/api/sms
Content-Type: application/json
{
  "smsId": "sms123",
  "sender": "+123456789",
  "message": "deviceId=dev001;temperature=25.5;humidity=67",
  "receivedAt": "2025-05-23T12:00:00Z",
  "deviceId": "dev001",
  "webhookSubscriptionId": "webhook123",
  "webhookEvent": "sms.received"
}

###

POST {{AgroMonitor_HostAddress}}/api/sms
Content-Type: application/json
x-signature: 7f0f827d-3a19-47f1-b91e-28fe79e5a4b7

{
  "smsId": "smsId",
  "sender": "+123456789",
  "message": "message",
  "receivedAt": "datetime",
  "deviceId": "deviceId",
  "webhookSubscriptionId": "webhookSubscriptionId",
  "webhookEvent": "sms.received"
}

###

POST {{AgroMonitor_HostAddress}}/api/sms
Content-Type: application/json
x-signature: 7f0f827d-3a19-47f1-b91e-28fe79e5a4b7
{
  "smsId": "smsId",
  "sender": "+123456789",
  "message": "message",
  "receivedAt": "datetime",
  "deviceId": "deviceId",
  "webhookSubscriptionId": "webhookSubscriptionId",
  "webhookEvent": "sms.received"
}

###
